# Generated by Django 4.2.1 on 2023-07-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='신고자 '),
        ),
    ]
